name: 'Pull request pre-conditions check'

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled, assigned, unassigned ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prPreConditions:
    runs-on: ubuntu-latest
    name: 'Check Pull Request pre-conditions'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: 'Install Yarn packages'
        run: 'yarn --immutable'
      - name: Validation
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
